### ISSUE TITLE
Trying to show a different marker using an article tag is not showing it

### ISSUE THREAD

**Issue by superknutsel** [superknutsel/donkeymap#16]
Tried to setup a marker based on a tag but it's not showing.

No Default icon is setup within the module on the Marker tab.

- created tag
- assigned tag to article
- configured tag/marker combination in the module on the "Tag markers" tab

Expected this marker to show but it's not.
Only after I remove the marker from the tab "Category markers" it is shown.
Can the order be that the tag marker override the default and category markers?

**Comment by pjdevries** [comment]
On the site where this was tested, it had to do with the View Level of the tagged article. Setting the View Level to Public solves the problem.

**Comment by pjdevries** [comment]
Was not the only problem. There was another problem with the logic that determines which icon to display. Solved and needs to be tested by @superknutsel.

**Comment by superknutsel** [comment]
Update 3.3.1 has fixed it. 
Close after new package is generated.

**Comment by pjdevries** [comment]
New release [v3.3.1](https://github.com/superknutsel/donkeymap/releases/tag/v3.3.1) published.
