### ISSUE TITLE
Trying to show a different marker using an article tag is overridden by the default marker

### ISSUE THREAD

**Issue by superknutsel** [superknutsel/donkeymap#17]
Tried to setup a marker based on a tag but it's overriden by the default marker.
If a marker icon is set in the "Marker" tab this is used. If no marker there, the default from the module is used.

No Default icon is setup within the module on the Marker tab.

    created tag
    assigned tag to article
    configured tag/marker combination in the module on the "Tag markers" tab

Expected this marker to show but it's not.

**Comment by pjdevries** [comment]
Works in my development environment.

Module:
- Category markers tab: _none_
- Tag markers tab: Cleaning/clean team 1 - **campingIcon**
- Marker tab: _no icon_

Articles:
- Category: Accomodation
- Tag: Cleaning/clean team 1 (2x)
- Accommodation tab: _no icon_

![image](https://github.com/user-attachments/assets/a8e1e4e0-89e9-46aa-9146-59313a93692b)
![image](https://github.com/user-attachments/assets/47706ada-ecb3-4063-89f1-9756be72abc9)

**Comment by superknutsel** [comment]
Solved, for now by design
