### ISSUE TITLE
When no category is selected the tag marker icon is not visible

### ISSUE THREAD

**Issue by superknutsel** [superknutsel/donkeymap#18]
Setup:

- On the marker tab in the module, nothing is added, not even a category
- On the tag tab there are tags selected with a marker icon

Expected is the articles that have this tag to be shown on the map with the icon that is selected in the "Tag markers" tab.

What is shown is just the text "Marker".
Inspecting the code shows it is probably an issue with the image path missing a / at the beginnen.

**Comment by pjdevries** [comment]
See also #17

**Comment by superknutsel** [comment]
Solved, for now by design
